# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f58f9d2e256eaf9d4e61600dba818985a6eb6a39aef7d9bb75f8db2f9ae414bc6e6d10068ae9d7a31c3e9909ba686b4fe80a37cc61d7c121f105cbf422c5c4f

test:
  secret_key_base: b91345bd8356e8b09b65007ce0806d632ea623411ec29936ff1d8c340d763f491fc78083dd6f7be2f73d6064be98bc2f05f2b500e19b1b9adc505ca294d6e02c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
